[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "dotnet MonsterDropWebAPI.dll"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
ASPNETCORE_ENVIRONMENT = "Production"
ASPNETCORE_URLS = "http://0.0.0.0:$PORT"